### ISSUE TITLE
By submitting this review you agree to use of your data as outlined in our privacy policy	

### ISSUE THREAD

**Issue by therampagerado** [getdatakick/pricealert#10]
Great module!

Thank you!

I believe that the word 'review' should be changed to 'request' in this case?!

**Comment by getdatakick** [comment]
> I believe that the word 'review' should be changed to 'request' in this case?!

You are right, this is obvious copy'n'paste error. Guess from what module :)

**Comment by therampagerado** [comment]
Yes, I imagined that may be the case :)
