### ISSUE TITLE
does not send mail or activate the alert

### ISSUE THREAD

**Issue by backamblock** [getdatakick/pricealert#7]
Hey there, i get the following errors in chrome debug console:

/modules/pricealert/ajax.php:1 Failed to load resource: the server responded with a status of 404 (Not Found)
VM8532:formatted:37 
POST https://ABCXYZ.de/modules/pricealert/ajax.php 404 (Not Found)
(anonymous) @ VM8532:formatted:37
send @ core.js:1571
ajax @ core.js:1492
(anonymous) @ pricealert.js:30
(anonymous) @ pricealert.js:9
r.submit @ pricealert.js:30
l @ pricealert.js:9
invokeGuardedCallback @ pricealert.js:17
invokeGuardedCallbackAndCatchFirstError @ pricealert.js:17
h @ pricealert.js:9
v @ pricealert.js:9
b @ pricealert.js:9
y @ pricealert.js:9
k @ pricealert.js:9
Qr @ pricealert.js:17
Ie @ pricealert.js:9
batchedUpdates @ pricealert.js:9
J @ pricealert.js:9
Me @ pricealert.js:9

---------------------------------------------------------
Firefox also reports me this errors:

Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://aaaaa.de/modules/revws/views/js/front-1_0_18.js
Source-Map-Adresse: front-1_0_18.js.map[Weitere Informationen]

Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://aaaaa.de/themes/core.js
Source-Map-Adresse: core.js.map[Weitere Informationen]

Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://aaaaa.de/modules/pricealert/views/js/pricealert.js
Source-Map-Adresse: pricealert.js.map[Weitere Informationen]

what can i do about it?
i have 2 languages in the shop so the url should be aaa.de/de/...
is this the issue/an issue or is this how it is supposed to be?

forgot to mention:
PHP 7.2 PS 1.7.4.2

greetings

**Comment by backamblock** [comment]
Maybe this has something to do with it, it is when i try to access the revws module in backoffice:

Parameter "id" for route "admin_product_form" must match "\d+" ("{ID}" given) to generate a corresponding URL.

Level | Channel | Message
-- | -- | --
INFO06:37:03 | php | User Deprecated: AdminMarketing is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/.
DEBUG06:37:03 | php | Warning: filemtime(): stat failed for /home/ilikevap/public_html/admin2131/themes/default/css/theme.css
CRITICAL06:37:05 | php | Uncaught Exception: Parameter "id" for route "admin_product_form" must match "\d+" ("{ID}" given) to generate a corresponding URL.
DEBUG06:37:05 | doctrine | SELECT name FROM pslx_module WHERE active = 1
INFO06:37:05 | php | User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".
CRITICAL06:37:05 | request | Uncaught PHP Exception Symfony\Component\Routing\Exception\InvalidParameterException: "Parameter "id" for route "admin_product_form" must match "\d+" ("{ID}" given) to generate a corresponding URL." at /home/ilikevap/public_html/vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/UrlGenerator.php line 146


Symfony\Component\Routing\Exception\InvalidParameterException:
Parameter "id" for route "admin_product_form" must match "\d+" ("{ID}" given) to generate a corresponding URL.

  at vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/UrlGenerator.php:146
  at Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(array('id' => 0), array('_controller' => 'PrestaShopBundle\\Controller\\Admin\\ProductController::formAction', '_legacy_controller' => 'AdminProducts', '_legacy_param_mapper_class' => 'PrestaShop\\PrestaShop\\Adapter\\Product\\AdminProductDataProvider', '_legacy_param_mapper_method' => 'mapLegacyParametersProductForm'), array('id' => '\\d+'), array(array('variable', '/', '\\d+', 'id'), array('text', '/product/form')), array('id' => '{ID}'), 'admin_product_form', 1, array(), array())
     (var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:154)
  at appDevDebugProjectContainerUrlGenerator->generate('admin_product_form', array('id' => '{ID}'), 1)
     (vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:240)
  at Symfony\Component\Routing\Router->generate('admin_product_form', array('id' => '{ID}'), 1)
     (src/PrestaShopBundle/Service/Routing/Router.php:48)
  at PrestaShopBundle\Service\Routing\Router->generate('admin_product_form', array('id' => '{ID}'))
     (classes/Link.php:712)
  at LinkCore->getAdminLink('AdminProducts', true, array('id_product' => '{ID}', 'updateproduct' => 1), array('id_product' => '{ID}', 'updateproduct' => 1, 'token' => '1fa2101760b688fa331d7b0dd4f29b79'))
     (modules/revws/controllers/admin/AdminRevwsBackendController.php:546)
  at AdminRevwsBackendController->getAdminLink('AdminProducts', array('id_product' => '{ID}', 'updateproduct' => 1))
     (modules/revws/controllers/admin/AdminRevwsBackendController.php:537)
  at AdminRevwsBackendController->getDrilldownTokens()
     (modules/revws/controllers/admin/AdminRevwsBackendController.php:79)
  at AdminRevwsBackendController->display()
     (classes/controller/Controller.php:275)
  at ControllerCore->run()
     (classes/Dispatcher.php:428)
  at DispatcherCore->dispatch()
     (admin2131/index.php:99)

**Comment by getdatakick** [comment]
Hi,

This is not a bug in a module, rather a misconfiguration of your server.

Since it's 404 error, than please check following

1) file ajax.php is present in /modules/pricealert/ajax.php
2) you might have some special rewrite rules in you .htaccess
3) you might have installed some security software that blocks this url

**Comment by backamblock** [comment]
hmm no special security software.
what shal i look for in htaccess? and in which folder? i found multiple in various directories with the search
